name: 'Phantomjs-CI'
description: 'test Phantomjs-CI'

runs:
  using: "composite"
  steps:

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: entrypoint.sh
      shell: bash